/* =========================================================================
   ESPECIFICACOES-EXTRAS.JS
   Gerado automaticamente pelo botão "Exportar para o Git" na Loja.
   Substitua o arquivo antigo por este no repositório e faça commit + push.
   [CORRIGIDO] 1) Reorganizado: a chave "2" estava vazia e deslocava todas as
   specs seguintes em 1 posição — cada spec agora está na chave = id do produto.
   2) ID 8 (RTX 5090) estava com specs de uma RTX 4080 — substituído pelos dados
   reais da RTX 5090 (fonte: NVIDIA + fichas técnicas, jul/2026).
   3) ID 172 (Kingston Fury Renegade 2TB) não tinha specs — preenchido com dados
   reais do fabricante/lojas (SFYRD/2000G, jul/2026).
========================================================================= */

const especificacoesExtras = {
    "1": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4080 16GB",
        "Arquitetura": "Ada Lovelace",
        "Núcleos CUDA": "9728",
        "Memória": "16 GB GDDR6X",
        "Interface de memória": "256-bit",
        "Clock base": "2205 MHz",
        "Clock boost": "2505 MHz",
        "Largura de banda": "716,8 GB/s",
        "TDP": "320 W",
        "Conector de energia": "1x 16-pin (PCIe 5.0)",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1",
        "Suporte a Ray Tracing": "Sim (3ª geração)",
        "Suporte DLSS": "DLSS 3 (Frame Generation)",
        "Dimensões": "336 x 137 x 61 mm (3 slots)",
        "Garantia": "3 anos"
    },
    "2": {
        "Fabricante": "Logitech",
        "Modelo": "G Pro X Superlight 2",
        "Cor": "Branco",
        "Sensor": "HERO 2",
        "DPI Máximo": "32.000",
        "Peso": "60g",
        "Conectividade": "LIGHTSPEED sem fio",
        "Bateria": "Até 95h",
        "Taxa de Polling": "2000hz",
        "Botões": "5",
        "Switches": "LIGHTFORCE híbrido ótico-mecânico",
        "Software": "Logitech G HUB"
    },
    "3": {
        "Fabricante": "Logitech ASTRO",
        "Modelo": "A10",
        "Cor": "Preto",
        "Drivers": "40mm, ímãs de neodímio",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Impedância": "32 Ω",
        "Sensibilidade (SPL)": "104 dB ± 3dB @ 1kHz",
        "Microfone": "6,0 mm unidirecional, flip-to-mute",
        "Conexão": "P2 3,5mm (removível)",
        "Som surround": "Não possui (estéreo 2.0)",
        "Estrutura": "Alumínio anodizado + policarbonato",
        "Peso (sem cabo)": "Over-ear (sobre a orelha)"
    },
    "4": {
        "Fabricante": "Corsair",
        "Modelo": "HS65 Surround",
        "Cor": "Preto",
        "Drivers": "50mm, neodímio, ajuste personalizado",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Impedância": "32 Ω @ 1kHz",
        "Sensibilidade": "111 dB ± 3dB",
        "Microfone": "Onidirecional, flip-to-mute",
        "Faixa de frequência do microfone": "100 Hz – 10 kHz",
        "Som surround": "Dolby Audio 7.1 (via USB + iCUE, PC/Mac)",
        "Peso": "282 g",
        "Software": "Corsair iCUE + SonarWorks SoundID"
    },
    "5": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 9 7950X",
        "Núcleos": "16",
        "Threads": "32",
        "Clock base": "4,5 GHz",
        "Clock boost": "5,7 GHz",
        "Cache L3": "64 MB",
        "TDP": "170W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "6": {
        "Fabricante": "SuperFrame",
        "Modelo": "SuperFrame Odin",
        "Cor": "Preto",
        "Drivers": "50mm",
        "Diâmetro do alto-falante": "50mm",
        "Impedância": "32 Ω ± 15%",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Sensibilidade (S.P.L)": "110 dB ± 3dB",
        "Diâmetro do microfone": "6,0 x 5,0 mm",
        "Sensibilidade do microfone": "42 dB ± 3dB",
        "Garantia": "1 Ano"
    },
    "7": {
        "Fabricante": "ASUS",
        "Modelo": "ROG Swift PG259QNR",
        "Tamanho da tela": "(25\" nominal)",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "Fast IPS",
        "Taxa de atualização": "360Hz",
        "Tempo de resposta": "1ms (GTG)",
        "Brilho": "400 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "NVIDIA G-SYNC (processador dedicado)",
        "Conexões": "1x DisplayPort 1.4, 1x HDMI 2.0",
        "Ajustes": "Inclinação, giro, pivô, altura"
    },
    "8": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 5090",
        "Arquitetura": "Blackwell (GB202)",
        "Núcleos CUDA": "21760",
        "Memória": "32 GB GDDR7",
        "Interface de memória": "512-bit",
        "Clock base": "2017 MHz",
        "Clock boost": "2407 MHz",
        "Largura de banda": "1.792 GB/s",
        "TDP": "575 W",
        "Conector de energia": "1x 16-pin (PCIe 5.0)",
        "Saídas de vídeo": "3x DisplayPort 2.1b, 1x HDMI 2.1b",
        "Suporte a Ray Tracing": "Sim (4ª geração)",
        "Suporte DLSS": "DLSS 4 (Multi Frame Generation)",
        "Dimensões": "304 x 137 x 40 mm (2 slots, Founders Edition)",
        "Garantia": "3 anos"
    },
    "9": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 9 9950X",
        "Núcleos": "16",
        "Threads": "32",
        "Clock base": "4,3 GHz",
        "Clock boost": "5,7 GHz",
        "Cache L3": "64 MB",
        "TDP": "170W",
        "Socket": "AM5",
        "Litografia": "4nm (TSMC)",
        "Memória suportada": "DDR5 até 5600MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "10": {
        "Fabricante": "Corsair",
        "Modelo": "Vengeance RGB",
        "Capacidade": "32GB (2x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "6200 MHz",
        "Latência (CL)": "CL36 (36-39-39-76)",
        "Tensão": "1,30 V",
        "Perfil de overclock": "Intel XMP 3.0",
        "Compatibilidade": "Intel série 600/700",
        "Iluminação": "RGB 10 zonas (10 LEDs/módulo)",
        "Dissipador": "Alumínio",
        "Software": "Corsair iCUE"
    },
    "11": {
        "Fabricante": "HyperX",
        "Modelo": "Cloud III",
        "Cor": "Preto / Preto-Vermelho",
        "Drivers": "53mm angulados, ímãs de neodímio",
        "Faixa de frequência": "10 Hz – 21 kHz",
        "Impedância": "64 Ω",
        "Sensibilidade": "100 dB SPL/mW @ 1kHz",
        "Distorção (THD)": "< 2%",
        "Microfone": "10mm, condensador eletreto, removível",
        "Padrão polar do microfone": "Unidirecional, com cancelamento de ruído",
        "Faixa de frequência do microfone": "50 Hz – 17 kHz",
        "Som espacial": "DTS Headphone:X (ativação vitalícia)"
    },
    "12": {
        "Fabricante": "AOC",
        "Modelo": "C27G4ZXE",
        "Tamanho da tela": "27",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "Fast VA (curvo 1500R)",
        "Taxa de atualização": "280Hz",
        "Tempo de resposta": "0,3ms (MPRT)",
        "Brilho": "300 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium, Adaptive-Sync",
        "Conexões": "HDMI, DisplayPort",
        "Ajustes": "Altura, inclinação, pivô"
    },
    "13": {
        "Fabricante": "SteelSeries",
        "Modelo": "Apex Pro",
        "Formato": "Full-size",
        "Switch": "OmniPoint Adjustable (Hall Effect)",
        "Tipo de atuação": "Mecânico ajustável (0,4mm–3,6mm)",
        "Efeitos RGB": "RGB dinâmica individual por tecla",
        "Layout": "US",
        "Keycaps": "ABS",
        "Anti-Ghosting": "100% N-Key Rollover",
        "Estrutura": "Liga de alumínio aeronáutico",
        "Conexão": "USB com fio",
        "Software": "SteelSeries Engine"
    },
    "14": {
        "Fabricante": "ASUS",
        "Modelo": "ROG Strix X870-E Gaming WiFi",
        "Chipset": "AMD X870E",
        "Socket": "AM5",
        "CPUs suportadas": "Ryzen 9000 / 8000 / 7000 Series",
        "Memória RAM": "4x DDR5, até 256GB, OC até 8000+MHz",
        "Slots PCIe": "1x PCIe 5.0 x16 + 1x PCIe 4.0 x4",
        "Slots M.2": "5 (3x PCIe 5.0 via CPU + 2x PCIe 4.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "18+2+2 fases, 110A por fase",
        "Rede": "WiFi 7 + Bluetooth + LAN 5Gb",
        "USB": "2x USB4, múltiplas USB 3.2 Gen2/Gen1"
    },
    "15": {
        "Fabricante": "Corsair",
        "Modelo": "RM1000x",
        "Potência": "1000W",
        "Certificação": "80 Plus Gold",
        "Eficiência": "Até 90%",
        "Modularidade": "Full Modular",
        "Ventoinha": "135mm, Levitação Magnética",
        "Padrão ATX": "ATX12V 2.53",
        "Conector ATX": "1x 24 pinos",
        "Conector PCIe": "6x",
        "Proteções": "OVP, UVP, SCP, OTP, OPP",
        "Conector SATA": "14x"
    },
    "16": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 5 5600",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "3,5 GHz",
        "Clock boost": "4,4 GHz",
        "Cache L3": "32 MB",
        "TDP": "65W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "17": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 5 5600X",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "3,7 GHz",
        "Clock boost": "4,6 GHz",
        "Cache L3": "32MB",
        "TDP": "65W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "18": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 5700X",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,4 GHz",
        "Clock boost": "4,6 GHz",
        "Cache L3": "32 MB",
        "TDP": "65W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "19": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 5800X",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,8 GHz",
        "Clock boost": "4,7 GHz",
        "Cache L3": "32 MB",
        "TDP": "105W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "20": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 5800X3D",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,4 GHz",
        "Clock boost": "4,5 GHz",
        "Cache L3": "96 MB (3D V-Cache)",
        "TDP": "105W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "21": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 5 7600",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "3,8 GHz",
        "Clock boost": "5,1 GHz",
        "Cache L3": "32MB",
        "TDP": "65W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "22": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 5 7600X",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "4,7 GHz",
        "Clock boost": "5,3 GHz",
        "Cache L3": "32 MB",
        "TDP": "105W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "23": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 7700",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,8 GHz",
        "Clock boost": "5,3 GHz",
        "Cache L3": "32 MB",
        "TDP": "65W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "24": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 7700X",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "4,5 GHz",
        "Clock boost": "5,4 GHz",
        "Cache L3": "32MB",
        "TDP": "105W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "25": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 7800X3D",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "4,2 GHz",
        "Clock boost": "5,0 GHz",
        "Cache L3": "96 MB (3D V-Cache)",
        "TDP": "120W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "26": {
        "Fabricante": "Intel",
        "Modelo": "i3-12100F",
        "Núcleos": "4",
        "Threads": "8",
        "Clock base": "3,3 GHz",
        "Clock boost": "4,3 GHz",
        "Cache L3": "12 MB",
        "TDP": "58W (89W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-4800",
        "Gráficos integrados": "Não possui"
    },
    "27": {
        "Fabricante": "Intel",
        "Modelo": "Core i5-12400F",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "2,5 GHz",
        "Clock boost": "4,4 GHz",
        "Cache L3": "18 MB",
        "TDP": "65W (117W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-4800",
        "Gráficos integrados": "Não possui"
    },
    "28": {
        "Fabricante": "Intel",
        "Modelo": "i5-13400F",
        "Núcleos": "10 (6P+4E)",
        "Threads": "16",
        "Clock base": "2,5 GHz",
        "Clock boost": "4,6 GHz",
        "Cache L3": "20 MB",
        "TDP": "65W (148W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-5200",
        "Gráficos integrados": "Não possui"
    },
    "29": {
        "Fabricante": "Intel",
        "Modelo": "i5-13600KF",
        "Núcleos": "14 (6P+8E)",
        "Threads": "20",
        "Clock base": "3,5 GHz",
        "Clock boost": "5,1 GHz",
        "Cache L3": "24 MB",
        "TDP": "125W (181W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-5600",
        "Gráficos integrados": "Não possui"
    },
    "30": {
        "Fabricante": "Intel",
        "Modelo": "i5-14600KF",
        "Núcleos": "14 (6P+8E)",
        "Threads": "20",
        "Clock base": "3,5 GHz",
        "Clock boost": "5,3 GHz",
        "Cache L3": "24 MB",
        "TDP": "125W (181W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-5600",
        "Gráficos integrados": "Não possui"
    },
    "31": {
        "Fabricante": "Intel",
        "Modelo": "Core i7-13700K",
        "Núcleos": "16 (8P+8E)",
        "Threads": "24",
        "Clock base": "3,4 GHz",
        "Clock boost": "5,4 GHz",
        "Cache L3": "30 MB",
        "TDP": "125W (253W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-5600",
        "Gráficos integrados": "Intel UHD 770"
    },
    "32": {
        "Fabricante": "Intel",
        "Modelo": "i9-13900K",
        "Núcleos": "24 (8P+16E)",
        "Threads": "32",
        "Clock base": "3,0 GHz",
        "Clock boost": "5,8 GHz",
        "Cache L3": "36 MB",
        "TDP": "125W (253W turbo)",
        "Socket": "LGA1700",
        "Litografia": "Intel 7 (10nm)",
        "Memória suportada": "DDR4-3200 / DDR5-5600",
        "Gráficos integrados": "Intel UHD 770"
    },
    "33": {
        "Fabricante": "HyperX",
        "Modelo": "Cloud Stinger 2",
        "Cor": "Preto",
        "Drivers": "40mm, neodímio, direcionais",
        "Faixa de frequência": "10 Hz – 25 kHz",
        "Impedância": "32,5 Ω",
        "Nível de pressão sonora": "95 dB SPL/mW @ 1kHz",
        "Microfone": "Condensador Electret, bidirecional, com cancelamento de ruído",
        "Peso": "272 g (menos de 300g)",
        "Recursos extras": "Conchas giratórias 90°, microfone swivel-to-mute",
        "Comprimento do cabo": "2 m",
        "Conexão": "3,5mm"
    },
    "34": {
        "Fabricante": "Logitech",
        "Modelo": "G335",
        "Cor": "Preto / Roxo",
        "Drivers": "40mm, neodímio",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Impedância": "36 Ω",
        "Sensibilidade": "87,5 dB SPL/mW",
        "Microfone": "Braço giratório, cardioide (unidirecional)",
        "Peso": "240 g",
        "Compatibilidade": "PC, PS4/PS5, Xbox, Nintendo Switch, Mobile",
        "Controles": "Flip-to-mute + roda de volume",
        "Almofadas": "Espuma viscoelástica com tecido esportivo"
    },
    "35": {
        "Fabricante": "Logitech",
        "Modelo": "G Pro X 2 Lightspeed",
        "Cor": "Preto",
        "Drivers": "50mm Grafeno",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Impedância": "38 Ω",
        "Sensibilidade": "87,8 dB SPL @ 1mW/1cm",
        "Microfone": "6mm cardioide, destacável",
        "Faixa de frequência do microfone": "100 Hz – 10 kHz",
        "Conectividade": "LIGHTSPEED Wireless, Bluetooth, P2 3,5mm",
        "Alcance sem fio": "Até 30 Metros",
        "Som surround": "DTS Headphone:X 2.0 (7.1)"
    },
    "36": {
        "Fabricante": "Redragon",
        "Modelo": "Zeus Pro H510 Pro",
        "Cor": "Preto",
        "Drivers": "53mm",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Impedância do áudio": "17 ± 15 Ω",
        "Sensibilidade": "111 ± 3 dB",
        "Microfone": "Omnidirecional, removível",
        "Bateria": "Até 18 horas",
        "Som surround": "7.1 Virtual",
        "Conexão": "2.4GHz / Bluetooth / USB-C",
        "Material das earpads": "Tecido"
    },
    "37": {
        "Fabricante": "Redragon",
        "Modelo": "Lamia 2 H320RGB",
        "Cor": "Preto",
        "Drivers": "40mm",
        "Faixa de frequência": "20 Hz – 20 kHz",
        "Impedância": "32 Ω",
        "Sensibilidade": "117 dB",
        "Microfone": "Omnidirecional",
        "Sensibilidade do microfone": "-40 ± 3 dB",
        "Conexão": "USB 2.0",
        "Comprimento do cabo": "2 m",
        "Som surround": "7.1 Virtual"
    },
    "38": {
        "Fabricante": "Razer",
        "Modelo": "BlackShark V2 X",
        "Cor": "Preto (também disponível em Verde, Branco, Quartzo)",
        "Drivers": "50mm Razer TriForce",
        "Faixa de frequência": "12 Hz – 28 kHz",
        "Impedância": "32 Ω @ 1kHz",
        "Diâmetro interno da concha": "63 x 43 mm",
        "Microfone": "Cardioide Razer HyperClear, dobrável",
        "Faixa de frequência do microfone": "100 Hz – 10 kHz",
        "Sensibilidade do microfone": "-42 dB V/Pa @ 1kHz",
        "Som surround": "7.1 Virtual (via software, só Windows 10 64-bit)",
        "Cancelamento de ruído": "Passivo avançado"
    },
    "39": {
        "Fabricante": "Logitech",
        "Modelo": "G203 Lightsync",
        "Cor": "Preto",
        "Sensor": "Óptico (genérico gaming-grade)",
        "DPI Máximo": "8.000",
        "Peso": "85g",
        "Conectividade": "Com fio (USB)",
        "Bateria": "-",
        "Taxa de Polling": "Padrão (não especificado)",
        "Botões": "6",
        "Switches": "Mecânicos com mola metálica",
        "Software": "Logitech G HUB"
    },
    "40": {
        "Fabricante": "Logitech",
        "Modelo": "G502 X",
        "Sensor": "HERO 25K",
        "DPI Máximo": "25.600",
        "Peso": "89g",
        "Conectividade": "Com fio (USB)",
        "Taxa de Polling": "1000Hz",
        "Botões": "13",
        "Switches": "LIGHTFORCE híbrido ótico-mecânico",
        "Software": "Logitech G HUB",
        "Cor": "Preto",
        "Bateria": "140 horas"
    },
    "41": {
        "Fabricante": "Razer",
        "Modelo": "DeathAdder V3",
        "Cor": "Preto",
        "Sensor": "Focus Pro 30K Optical",
        "DPI Máximo": "30.000",
        "Peso": "59g",
        "Conectividade": "Com fio (cabo Speedflex)",
        "Bateria": "70 horas",
        "Taxa de Polling": "Até 8000Hz",
        "Botões": "6",
        "Switches": "Ópticos Gen-3",
        "Software": "Razer Synapse"
    },
    "42": {
        "Fabricante": "Razer",
        "Modelo": "Cobra",
        "Cor": "Preto",
        "Sensor": "PixArt PAW3349 Optical",
        "DPI Máximo": "8.500",
        "Peso": "58g",
        "Conectividade": "Com fio (cabo Speedflex)",
        "Bateria": "-",
        "Taxa de Polling": "Padrão (não especificado)",
        "Botões": "6",
        "Switches": "Ópticos Gen-3 (90M cliques)",
        "Software": "Razer Synapse"
    },
    "43": {
        "Fabricante": "HyperX",
        "Modelo": "Pulsefire Haste 2",
        "Cor": "Preto",
        "Sensor": "HyperX 26K (PixArt PAW3395)",
        "DPI Máximo": "26.000",
        "Peso": "61g",
        "Conectividade": "2,4GHz + Bluetooth",
        "Bateria": "Até 100h",
        "Taxa de Polling": "1000Hz",
        "Botões": "6",
        "Switches": "HyperX (100M cliques)",
        "Software": "HyperX NGENUITY"
    },
    "44": {
        "Fabricante": "Redragon",
        "Modelo": "Cobra M711 V2",
        "Cor": "Preto",
        "Sensor": "PixArt PMW3360",
        "DPI Máximo": "24.000 (interpolado)",
        "Peso": "82g",
        "Conectividade": "Com fio (USB)",
        "Bateria": "-",
        "Taxa de Polling": "125/250/500/1000Hz",
        "Botões": "7 programáveis (9 no total)",
        "Switches": "Ópticos LK (50M cliques)",
        "Software": "Redragon (proprietário)"
    },
    "45": {
        "Fabricante": "Redragon",
        "Modelo": "Storm Pro M808-KS",
        "Sensor": "PixArt PAW3335",
        "Cor": "Preto",
        "DPI Máximo": "16.000",
        "Peso": "86g",
        "Conectividade": "2,4GHz + com fio",
        "Bateria": "Recarregável 700mAh",
        "Taxa de Polling": "125/250/500/1000Hz",
        "Botões": "7",
        "Switches": "Huano",
        "Software": "Redragon (proprietário)"
    },
    "46": {
        "Fabricante": "Razer",
        "Modelo": "Viper V3 Pro",
        "Sensor": "Focus Pro 35K Optical Gen-2",
        "DPI Máximo": "35.000",
        "Conectividade": "Wireless (dongle HyperPolling) + USB-C",
        "Peso": "54g",
        "Taxa de Polling": "Até 8000Hz (sem fio)",
        "Botões": "6",
        "Switches": "Ópticos Gen-3 (90M cliques)",
        "Bateria": "Até 95h (1000Hz) / 17h (8000Hz)",
        "Pés (Feet)": "PTFE 100%",
        "Software": "Razer Synapse"
    },
    "47": {
        "Fabricante": "SteelSeries",
        "Modelo": "Aerox 5 Wireless",
        "Cor": "Preto",
        "Sensor": "TrueMove Air (PixArt PAW3335)",
        "DPI Máximo": "18.000",
        "Peso": "74g",
        "Conectividade": "2,4GHz + Bluetooth 5.0",
        "Bateria": "Até 180h",
        "Taxa de Polling": "1000Hz",
        "Botões": "9",
        "Switches": "Golden Micro IP54 (80M cliques)",
        "Software": "SteelSeries GG"
    },
    "48": {
        "Fabricante": "Corsair",
        "Modelo": "M75 Wireless",
        "Cor": "Preto",
        "Sensor": "Marksman Optical",
        "DPI Máximo": "26.000",
        "Peso": "89g",
        "Conectividade": "Slipstream 2,4GHz + Bluetooth + com fio",
        "Bateria": "Até 105h (RGB off) / 210h (Bluetooth)",
        "Taxa de Polling": "2000Hz",
        "Botões": "6",
        "Switches": "Quickstrike ópticos (100M cliques)",
        "Software": "Corsair iCUE"
    },
    "49": {
        "Fabricante": "ASUS",
        "Modelo": "Keris II Ace",
        "Cor": "Preto",
        "Sensor": "AimPoint Pro",
        "DPI Máximo": "42.000",
        "Peso": "54g",
        "Conectividade": "Tri-mode (2,4GHz / Bluetooth / USB-C)",
        "Bateria": "Até 107h (2,4GHz)",
        "Taxa de Polling": "Até 4000Hz (com Polling Rate Booster)",
        "Botões": "5",
        "Switches": "Ópticos ROG (100M cliques)",
        "Software": "Armoury Crate"
    },
    "50": {
        "Fabricante": "Glorious",
        "Modelo": "Model O 2 Wireless",
        "Cor": "Preto",
        "Sensor": "BAMF 2.0 (PixArt PAW3395)",
        "DPI Máximo": "26.000",
        "Peso": "68g",
        "Conectividade": "2,4GHz + Bluetooth + com fio",
        "Bateria": "Até 110h (2,4GHz) / 210h (Bluetooth)",
        "Taxa de Polling": "1000hz",
        "Botões": "6",
        "Switches": "Glorious (80M cliques)",
        "Software": "Glorious CORE"
    },
    "51": {
        "Fabricante": "Cooler Master",
        "Modelo": "MM712",
        "Cor": "Preto",
        "Sensor": "PixArt PAW3370",
        "DPI Máximo": "19.000",
        "Peso": "59g",
        "Conectividade": "2,4GHz + Bluetooth + com fio",
        "Bateria": "Até 180h (Bluetooth) / 80h (2,4GHz)",
        "Taxa de Polling": "1000Hz (2,4GHz/com fio) / 125Hz (Bluetooth)",
        "Botões": "6",
        "Switches": "LK 2.0 ópticos (70M cliques)",
        "Software": "Cooler Master MasterPlus+"
    },
    "52": {
        "Fabricante": "Alienware",
        "Modelo": "Pro Wireless Gaming",
        "Cor": "Branco",
        "Sensor": "PixArt PAW3395",
        "DPI Máximo": "26.000",
        "Peso": "59g",
        "Conectividade": "2,4GHz + USB-C",
        "Bateria": "Até 120h (1000Hz) / 32h (4000Hz)",
        "Taxa de Polling": "Até 4000Hz (sem fio) / 8000Hz (com fio)",
        "Botões": "6",
        "Switches": "Ópticos com sistema magnético (70M cliques)",
        "Software": "Alienware Command Center"
    },
    "53": {
        "Fabricante": "MSI",
        "Modelo": "Versa 300 Wireless",
        "Cor": "Preto",
        "Sensor": "PixArt PAW3395DM",
        "DPI Máximo": "26.000",
        "Peso": "56g",
        "Conectividade": "SWIFTSPEED 2,4GHz + Bluetooth 5.3 + com fio",
        "Bateria": "Até 200h",
        "Taxa de Polling": "1000hz",
        "Botões": "6",
        "Switches": "OMRON (60M cliques)",
        "Software": "MSI Center"
    },
    "54": {
        "Fabricante": "Redragon",
        "Modelo": "Kumara K552 RGB",
        "Formato": "TKL (Tenkeyless)",
        "Switch": "Outemu Blue (removível)",
        "Tipo de atuação": "Mecânico, clique audível",
        "Efeitos RGB": "19 modos de iluminação",
        "Layout": "ABNT2",
        "Keycaps": "ABS Double-Shot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Metal + Plástico ABS",
        "Conexão": "USB com fio (banhado a ouro)",
        "Software": "Redragon (RGB/macros)"
    },
    "55": {
        "Fabricante": "Redragon",
        "Modelo": "Fizz K617 RGB",
        "Formato": "60%",
        "Switch": "Outemu (Red/Brown/Blue, hot-swappable)",
        "Tipo de atuação": "Mecânico",
        "Efeitos RGB": "11 efeitos dinâmicos",
        "Layout": "ABNT2",
        "Keycaps": "ABS Doubleshot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Plástico ABS",
        "Conexão": "USB-C removível",
        "Software": "Redragon (RGB/macros)"
    },
    "56": {
        "Fabricante": "HyperX",
        "Modelo": "Alloy Origins Core",
        "Formato": "TKL (Tenkeyless)",
        "Switch": "HyperX Red (Linear)",
        "Tipo de atuação": "Mecânico linear (força 45g, 1,8mm)",
        "Efeitos RGB": "RGB por tecla, 5 níveis de brilho",
        "Layout": "ABNT2",
        "Keycaps": "ABS",
        "Anti-Ghosting": "100% N-Key Rollover",
        "Estrutura": "Alumínio grau aeronáutico",
        "Conexão": "USB-C removível",
        "Software": "HyperX NGENUITY"
    },
    "57": {
        "Fabricante": "Logitech",
        "Modelo": "G413 SE",
        "Formato": "Full Size",
        "Switch": "Mecânico Tactile (proprietário)",
        "Tipo de atuação": "Mecânico tátil",
        "Efeitos RGB": "Não possui (LED branco monocromático)",
        "Layout": "ABNT2",
        "Keycaps": "PBT de alta durabilidade",
        "Anti-Ghosting": "6-Key Rollover",
        "Estrutura": "Alumínio escovado",
        "Conexão": "USB com fio",
        "Software": "Não requer (plug-and-play)"
    },
    "58": {
        "Fabricante": "Logitech",
        "Modelo": "G Pro X TKL Lightspeed",
        "Formato": "TKL (Tenkeyless)",
        "Switch": "GX Brown Tactile",
        "Tipo de atuação": "Mecânico tátil",
        "Efeitos RGB": "RGB LIGHTSYNC",
        "Layout": "US",
        "Keycaps": "PBT Double-shot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Base em alumínio-magnésio",
        "Conexão": "LIGHTSPEED Wireless, Bluetooth, USB-C",
        "Software": "Logitech G HUB"
    },
    "59": {
        "Fabricante": "Corsair",
        "Modelo": "K70 Core RGB",
        "Formato": "Full-size",
        "Switch": "Corsair MLX Red (Linear)",
        "Tipo de atuação": "Mecânico linear (força 45g, 1,9mm)",
        "Efeitos RGB": "RGB por tecla via iCUE",
        "Layout": "ABNT2",
        "Keycaps": "ABS",
        "Anti-Ghosting": "Full NKRO",
        "Estrutura": "Placa superior em alumínio",
        "Conexão": "USB com fio",
        "Software": "Corsair iCUE"
    },
    "60": {
        "Fabricante": "Corsair",
        "Modelo": "K70 RGB PRO",
        "Formato": "Full Size",
        "Switch": "CHERRY MX Red",
        "Tipo de atuação": "Mecânico linear",
        "Efeitos RGB": "RGB por tecla (até 20 camadas)",
        "Layout": "ANSI / PT",
        "Keycaps": "PBT Double-Shot PRO",
        "Anti-Ghosting": "Full NKRO",
        "Estrutura": "Alumínio durável",
        "Conexão": "USB com fio",
        "Software": "Corsair iCUE"
    },
    "61": {
        "Fabricante": "Razer",
        "Modelo": "BlackWidow V4",
        "Formato": "Full-size",
        "Switch": "Razer Green (Clicky) / Yellow (Linear)",
        "Tipo de atuação": "Mecânico",
        "Iluminação": "Razer Chroma RGB + underglow",
        "Layout": "US (ABNT2 disponível em outras versões)",
        "Keycaps": "ABS Doubleshot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Liga de alumínio 5052",
        "Conexão": "USB-C removível",
        "Extras": "Apoio de pulso magnético incluso · roda multimídia com 4 botões · 5 teclas macro dedicadas · polling rate até 8.000Hz"
    },
    "62": {
        "Fabricante": "SteelSeries",
        "Modelo": "Apex Pro TKL Wireless",
        "Formato": "TKL (87 teclas)",
        "Switch": "OmniPoint 2.0 Adjustable HyperMagnetic",
        "Tipo de atuação": "Mecânico ajustável (0,2mm–3,8mm)",
        "Efeitos RGB": "RGB PrismSync individual",
        "Layout": "US",
        "Keycaps": "PBT Double-shot",
        "Anti-Ghosting": "Full N-Key Rollover",
        "Estrutura": "Alumínio Série 5000 aeronáutico",
        "Conexão": "USB-C, 2,4GHz Wireless, Bluetooth",
        "Software": "SteelSeries GG"
    },
    "63": {
        "Fabricante": "HyperX",
        "Modelo": "Alloy Origins 65",
        "Formato": "65%",
        "Switch": "HyperX Red (Linear) / Aqua (Tátil)",
        "Tipo de atuação": "Mecânico",
        "Efeitos RGB": "RGB individual por tecla, LED exposto",
        "Layout": "US",
        "Keycaps": "PBT Double-shot",
        "Anti-Ghosting": "100% N-Key Rollover",
        "Estrutura": "Alumínio aeronáutico",
        "Conexão": "USB-C removível",
        "Software": "HyperX NGENUITY"
    },
    "64": {
        "Fabricante": "ASUS",
        "Modelo": "Strix Scope II 96 Wireless",
        "Formato": "96%",
        "Switch": "ROG NX (hot-swappable)",
        "Tipo de atuação": "Mecânico",
        "Efeitos RGB": "Aura Sync, RGB individual por tecla",
        "Layout": "US/ANSI",
        "Keycaps": "PBT Double-shot / ABS UV-coated",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Espuma de amortecimento integrada",
        "Conexão": "Bluetooth, 2.4GHz SpeedNova, USB-C",
        "Software": "ASUS Armoury Crate"
    },
    "65": {
        "Fabricante": "Keychron",
        "Modelo": "K2 Pro",
        "Formato": "75% (84 teclas)",
        "Switch": "Keychron K Pro (hot-swappable)",
        "Tipo de atuação": "Mecânico",
        "Efeitos RGB": "22 tipos de retroiluminação RGB",
        "Layout": "ANSI (teclas Mac e Windows inclusas)",
        "Keycaps": "PBT Double-shot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Alumínio + base ABS",
        "Conexão": "Bluetooth 5.1 + USB-C",
        "Software": "QMK/VIA (Keychron Launcher)"
    },
    "66": {
        "Fabricante": "Redragon",
        "Modelo": "Fizz Pro K616",
        "Formato": "60%",
        "Switch": "Redragon Red/Blue/Brown (hot-swappable)",
        "Tipo de atuação": "Mecânico",
        "Efeitos RGB": "20 modos RGB Chroma Mk.II",
        "Layout": "ABNT2",
        "Keycaps": "ABS Doubleshot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Plástico ABS reforçado",
        "Conexão": "2,4GHz Wireless, Bluetooth 5.0, USB-C",
        "Software": "Redragon Pro"
    },
    "67": {
        "Fabricante": "Corsair",
        "Modelo": "K65 Plus Wireless",
        "Formato": "75%",
        "Switch": "Corsair MLX Red (Linear, hot-swappable)",
        "Tipo de atuação": "Mecânico linear",
        "Efeitos RGB": "RGB saturado com legendas visíveis",
        "Layout": "ANSI",
        "Keycaps": "PBT dye-sub",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Dupla camada de amortecimento sonoro",
        "Conexão": "2.4GHz wireless, Bluetooth, USB-C",
        "Software": "Corsair iCUE"
    },
    "68": {
        "Fabricante": "Razer",
        "Modelo": "Huntsman V3 Pro TKL",
        "Formato": "TKL (Tenkeyless)",
        "Switch": "Razer Analog Optical Gen-2",
        "Tipo de atuação": "Óptico-analógico ajustável (0,1mm–4,0mm)",
        "Efeitos RGB": "Razer Chroma RGB",
        "Layout": "ANSI (US)",
        "Keycaps": "PBT Double-shot",
        "Anti-Ghosting": "N-Key Rollover",
        "Estrutura": "Alumínio escovado",
        "Conexão": "USB-C",
        "Software": "Razer Synapse"
    },
    "69": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 3050",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Núcleos CUDA": "2560",
        "Clock base": "1552 MHz",
        "Clock boost": "1777 MHz",
        "TDP": "130W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "70": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 3060 Ventus 2X",
        "Memoria": "12 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "192-bit",
        "Núcleos CUDA": "3584",
        "Clock base": "1320 MHz",
        "Clock boost": "1777 MHz",
        "TDP": "170W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "71": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 3060 Ti Eagle",
        "Memoria": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "4864",
        "Clock base": "1410 MHz",
        "Clock boost": "1665 MHz",
        "TDP": "200W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "72": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4060 Dual OC",
        "Memória": "8GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Núcleos CUDA": "3072",
        "Clock base": "1830 MHz",
        "Clock boost": "2460 MHz",
        "TDP": "115W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "73": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4060 Ti Gaming X",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Núcleos CUDA": "4352",
        "Clock base": "2310 MHz",
        "Clock boost": "2535 MHz",
        "TDP": "160W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "74": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4070 WindForce OC",
        "Memória": "12 GB",
        "Tipo de memória": "GDDR6X",
        "Barramento de memória": "192-bit",
        "Núcleos CUDA": "5888",
        "Clock base": "1920 MHz",
        "Clock boost": "2475 MHz",
        "TDP": "200W",
        "Conector de energia": "1x 16-pin (12VHPWR)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "75": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4070 SUPER",
        "Memória": "12 GB",
        "Tipo de memória": "GDDR6X",
        "Barramento de memória": "192-bit",
        "Núcleos CUDA": "7168",
        "Clock base": "1980 MHz",
        "Clock boost": "2475 MHz",
        "TDP": "220W",
        "Conector de energia": "1x 16-pin (12VHPWR)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "76": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4070 Ti SUPER",
        "Memória": "16 GB",
        "Tipo de memória": "GDDR6X",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "8448",
        "Clock base": "2310 MHz",
        "Clock boost": "2610 MHz",
        "TDP": "285W",
        "Conector de energia": "1x 16-pin (12VHPWR)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "77": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4080 SUPER Aero OC",
        "Memória": "16 GB",
        "Tipo de memória": "GDDR6X",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "10240",
        "Clock base": "2295 MHz",
        "Clock boost": "2550 MHz",
        "TDP": "320W",
        "Conector de energia": "1x 16-pin (12VHPWR)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "78": {
        "Fabricante": "AMD",
        "Modelo": "RX 6600 Challenger D",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Stream Processors": "1792",
        "Clock (game)": "2044 MHz",
        "Clock boost": "2491 MHz",
        "TDP": "132W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.1"
    },
    "79": {
        "Fabricante": "AMD",
        "Modelo": "RX 6650 XT Pulse",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Stream Processors": "2048",
        "Clock (game)": "2410 MHz",
        "Clock boost": "2635 MHz",
        "TDP": "180W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.1"
    },
    "80": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 6700 XT",
        "Memória": "12 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "192-bit",
        "Stream Processors": "2560",
        "Clock (game)": "2424 MHz",
        "Clock boost": "2581 MHz",
        "TDP": "230W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.1"
    },
    "81": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 6750 XT",
        "Memória": "12 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "192-bit",
        "Stream Processors": "2560",
        "Clock (game)": "2153 MHz",
        "Clock boost": "2600 MHz",
        "TDP": "250W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.1"
    },
    "82": {
        "Fabricante": "AMD",
        "Modelo": "X 7600 Steel Legend",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Stream Processors": "2048",
        "Clock (game)": "2250 MHz",
        "Clock boost": "2655 MHz",
        "TDP": "165W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 2.1, 1x HDMI 2.1"
    },
    "83": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 7700 XT",
        "Memoria": "12GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "192-bit",
        "Stream Processors": "3456",
        "Clock (game)": "2171 MHz",
        "Clock boost": "2544 MHz",
        "TDP": "245W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 2.1, 1x HDMI 2.1"
    },
    "84": {
        "Fabricante": "ASUS",
        "Modelo": "Prime B550M-A",
        "Chipset": "AMD B550",
        "Socket": "AM4",
        "CPUs suportadas": "Ryzen 5000/4000G/3000 Series",
        "Memória RAM": "4x DDR4, até 128GB, OC até 4866MHz",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x16 (x4) + 2x PCIe 3.0 x1",
        "Slots M.2": "2 (1x PCIe 4.0 via CPU + 1x PCIe 3.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "Básico, entrada (sem DrMOS reforçado)",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen2 Type-A"
    },
    "85": {
        "Fabricante": "Gigabyte",
        "Modelo": "B550M DS3H",
        "Chipset": "AMD B550",
        "Socket": "AM4",
        "CPUs suportadas": "Ryzen 5000/4000G/3000 Series",
        "Memória RAM": "4x DDR4, até 128GB",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x16 (x4) + 1x PCIe 3.0 x1",
        "Slots M.2": "2 (1x PCIe 4.0 via CPU + 1x PCIe 3.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "5 fases, entrada/intermediário",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen1"
    },
    "86": {
        "Fabricante": "MSI",
        "Modelo": "B550 Tomahawk",
        "Chipset": "AMD B550",
        "Socket": "AM4",
        "CPUs suportadas": "Ryzen 5000/4000G/3000 Series",
        "Memória RAM": "4x DDR4, até 128GB, OC até 4866+MHz",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x16 (x4) + 2x PCIe 3.0 x1",
        "Slots M.2": "2 (1x PCIe 4.0 via CPU + 1x PCIe 3.0 via chipset)",
        "Portas SATA": "6x SATA 6Gb/s",
        "VRM (fases)": "10+2+1 fases, 60A",
        "Rede": "Sem WiFi nativo, LAN 2.5Gb + 1Gb",
        "USB": "USB 3.2 Gen2 Type-C"
    },
    "87": {
        "Fabricante": "ASUS",
        "Modelo": "TUF Gaming B650M-Plus WiFi",
        "Chipset": "AMD B650",
        "Socket": "AM5",
        "CPUs suportadas": "Ryzen 9000/8000/7000 Series",
        "Memória RAM": "4x DDR5, até 128GB, suporte EXPO",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 4.0 x1",
        "Slots M.2": "2 (1x PCIe 5.0 via CPU + 1x PCIe 4.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "12+2+2 fases, 60A",
        "Rede": "WiFi 6 + Bluetooth + LAN 2.5Gb",
        "USB": "USB4 (header), USB 3.2 Gen2 Type-C"
    },
    "88": {
        "Fabricante": "Gigabyte",
        "Modelo": "B650 Aorus Elite AX",
        "Chipset": "AMD B650",
        "Socket": "AM5",
        "CPUs suportadas": "Ryzen 9000/8000/7000 Series",
        "Memória RAM": "4x DDR5, até 128GB, EXPO/XMP até 6666+MHz",
        "Slots PCIe": "1x PCIe 4.0 x16 + 2x PCIe 3.0 x16 (x1)",
        "Slots M.2": "3 (1x PCIe 5.0 via CPU + 2x PCIe 3.0/4.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "14 fases Twin Digital, 70A",
        "Rede": "WiFi 6E + Bluetooth 5.2 + LAN 2.5Gb",
        "USB": "USB 3.2 Gen2x2 Type-C"
    },
    "89": {
        "Fabricante": "MSI",
        "Modelo": "PRO B760M-A WiFi DDR5",
        "Chipset": "Intel B760",
        "Socket": "LGA 1700",
        "CPUs suportadas": "Intel Core 14ª/13ª/12ª geração",
        "Memória RAM": "4x DDR5, até 192GB",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x1",
        "Slots M.2": "2 (PCIe 4.0)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "8 fases",
        "Rede": "WiFi 6 + Bluetooth + LAN 1Gb",
        "USB": "USB 3.2 Gen2 Type-C"
    },
    "90": {
        "Fabricante": "ASUS",
        "Modelo": "Prime B760M-A D4",
        "Chipset": "Intel B760",
        "Socket": "LGD 1700",
        "CPUs suportadas": "Intel Core 14ª/13ª/12ª geração",
        "Memória RAM": "4x DDR4, até 128GB",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x1",
        "Slots M.2": "2 (1x PCIe 4.0 via CPU + 1x PCIe 3.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "8+1 fases DrMOS",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen2 Type-C"
    },
    "91": {
        "Fabricante": "Gigabyte",
        "Modelo": "Z790 Aorus Elite AX",
        "Chipset": "Intel Z790",
        "Socket": "LGA 1700",
        "CPUs suportadas": "Intel Core 14ª/13ª/12ª geração",
        "Memória RAM": "4x DDR5, até 256GB, XMP até 7600+MHz",
        "Slots PCIe": "1x PCIe 5.0 x16 + 2x PCIe 4.0 x16 (x4)",
        "Slots M.2": "4 (PCIe 4.0)",
        "Portas SATA": "6x SATA 6Gb/s",
        "VRM (fases)": "16+1+2 fases Twin Digital, 70A",
        "Rede": "WiFi 6E + Bluetooth 5 + LAN 2.5GB",
        "USB": "USB 3.2 Gen2x2 Type-C"
    },
    "92": {
        "Fabricante": "Kingston (FURY)",
        "Modelo": "Fury Beast",
        "Capacidade": "8GB (1x8GB)",
        "Tipo de memória": "DDR4",
        "Frequência": "3200 MHz",
        "Latência (CL)": "CL16 (16-18-18)",
        "Tensão": "1,35V",
        "Perfil de overclock": "Intel XMP 2.0",
        "Compatibilidade": "Intel/AMD Ryzen",
        "Iluminação": "Sem RGB (versão padrão)",
        "Dissipador": "Baixo Perfil",
        "Garantia": "Vitalícia (fabricante)"
    },
    "93": {
        "Fabricante": "Kingston (FURY)",
        "Modelo": "Fury Beast",
        "Capacidade": "16GB (2x8GB)",
        "Tipo de memória": "DDR4",
        "Frequência": "3200 MHz",
        "Latência (CL)": "CL16 (16-18-18-38)",
        "Tensão": "1,35V",
        "Perfil de overclock": "Intel XMP 2.0",
        "Compatibilidade": "Intel/AMD Ryzen",
        "Iluminação": "Sem RGB (versão padrão)",
        "Dissipador": "Baixo perfil",
        "Garantia": "Vitalícia (fabricante)"
    },
    "94": {
        "Fabricante": "Kingston",
        "Modelo": "Fury Beast",
        "Capacidade": "16GB (1x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "5600 MHz",
        "Latência (CL)": "CL40 (40-40-40)",
        "Tensão": "1,25 V",
        "Perfil de overclock": "Intel XMP 3.0",
        "Compatibilidade": "Intel/AMD (placas DDR5)",
        "Iluminação": "Sem RGB (versão padrão)",
        "Dissipador": "Baixo perfil",
        "Software": "Não requer"
    },
    "95": {
        "Fabricante": "Corsair",
        "Modelo": "Vengeance LPX",
        "Capacidade": "16GB (2x8GB)",
        "Tipo de memória": "DDR4",
        "Frequência": "3200 MHz",
        "Latência (CL)": "CL16 (16-18-18-36)",
        "Tensão": "1,35V",
        "Perfil de overclock": "Intel XMP 2.0",
        "Compatibilidade": "Intel 100/200/300/X299, AMD 300/400/X570",
        "Iluminação": "Sem RGB",
        "Dissipador": "Alumínio anodizado, baixo perfil",
        "Garantia": "Vitalícia (fabricante)"
    },
    "96": {
        "Fabricante": "Corsair",
        "Modelo": "Vengeance RGB",
        "Capacidade": "32GB (2x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "6000 MHz",
        "Latência (CL)": "CL38 (38-38-38-76)",
        "Tensão": "1,25 V",
        "Perfil de overclock": "Intel XMP 3.0",
        "Compatibilidade": "Intel série 600/700",
        "Iluminação": "RGB 10 zonas (10 LEDs/módulo)",
        "Dissipador": "Alumínio anodizado preto",
        "Software": "Corsair iCUE"
    },
    "97": {
        "Fabricante": "XPG (ADATA)",
        "Modelo": "Gammix D35",
        "Capacidade": "16GB (1x16GB)",
        "Tipo de memória": "DDR4",
        "Frequência": "3200 MHz",
        "Latência (CL)": "CL16 (16-20-20)",
        "Tensão": "1,35 V",
        "Perfil de overclock": "Intel XMP 2.0",
        "Compatibilidade": "Intel/AMD (plataformas recentes)",
        "Iluminação": "Sem RGB",
        "Dissipador": "Baixo perfil, design triangular",
        "Garantia": "10 Anos"
    },
    "98": {
        "Fabricante": "XPG",
        "Modelo": "Lancer RGB",
        "Capacidade": "16GB (1x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "6000 MHz",
        "Latência (CL)": "CL30 (30-40-40)",
        "Tensão": "1,25 V – 1,45 V",
        "Perfil de overclock": "Intel XMP 3.0",
        "Compatibilidade": "AMD AM5, Intel (12ª geração+)",
        "Iluminação": "RGB customizável (XPG Prime)",
        "Dissipador": "Alumínio",
        "Software": "XPG Prime"
    },
    "99": {
        "Fabricante": "Crucial",
        "Modelo": "Pro",
        "Capacidade": "16GB (1x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "5600 MHz",
        "Latência (CL)": "CL46",
        "Tensão": "1,1V",
        "Perfil de overclock": "Intel XMP 3.0 / AMD EXPO",
        "Compatibilidade": "Intel 12ª/13ª/14ª Gen, AMD Ryzen 7000+",
        "Iluminação": "Sem RGB",
        "Dissipador": "-",
        "Garantia": "Vitalícia (fabricante)"
    },
    "100": {
        "Fabricante": "TeamGroup",
        "Modelo": "T-Force Vulcan Z",
        "Capacidade": "16GB (2x8GB)",
        "Tipo de memória": "DDR4",
        "Frequência": "3200 MHz",
        "Latência (CL)": "CL16 (16-18-18-38)",
        "Tensão": "1,35 V",
        "Perfil de overclock": "Intel XMP 2.0",
        "Compatibilidade": "Intel e AMD",
        "Iluminação": "Sem RGB",
        "Dissipador": "Alumínio anodizado, 0,8mm",
        "Garantia": "Vitalícia (fabricante)"
    },
    "101": {
        "Fabricante": "TeamGroup",
        "Modelo": "T-Force Delta RGB",
        "Capacidade": "32GB (2x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "6000 MHz",
        "Latência (CL)": "CL30 (30-36-36-76)",
        "Tensão": "1,35 V",
        "Perfil de overclock": "Intel XMP 3.0 / AMD EXPO",
        "Compatibilidade": "ASRock, ASUS, Biostar, Gigabyte, MSI",
        "Iluminação": "RGB 120° ultra-wide",
        "Dissipador": "Alumínio com PMIC reforçado",
        "Garantia": "1 Ano"
    },
    "102": {
        "Fabricante": "G.Skill",
        "Modelo": "Ripjaws S5",
        "Capacidade": "32GB (2x16GB)",
        "Tipo de memória": "DDR5",
        "Frequência": "6000 MHz",
        "Latência (CL)": "CL30 (30-40-40-96)",
        "Tensão": "1,35V",
        "Perfil de overclock": "Intel XMP 3.0",
        "Compatibilidade": "Intel Z690/Z790/Z890, B760/B860",
        "Iluminação": "Sem RGB",
        "Dissipador": "Alumínio, baixo perfil (33mm)",
        "Garantia": "Vitalícia (fabricante)"
    },
    "103": {
        "Fabricante": "Corsair",
        "Modelo": "CV650",
        "Potência": "650W",
        "Certificação": "80 Plus Bronze",
        "Eficiência": "Até 88%",
        "Modularidade": "Não modular",
        "Ventoinha": "120mm",
        "Padrão ATX": "ATX12V v2.31",
        "Conector ATX": "1x 24 pinos",
        "Conector PCIe": "1x 8 pinos (6+2)",
        "Conector SATA": "7x",
        "MTBF": "100.000 horas"
    },
    "104": {
        "Fabricante": "MSI",
        "Modelo": "MAG A650BN 650W",
        "Potência": "650W",
        "Certificação": "80 Plus Bronze",
        "Eficiência": "Até 85%",
        "Modularidade": "Não modular",
        "Ventoinha": "120mm, mancal de manga",
        "Padrão ATX": "ATX V2.4",
        "Conector ATX": "1x 24 pinos (20+4)",
        "Conector PCIe": "2x 6+2 pinos",
        "Conector SATA": "5x",
        "Proteções": "OCP, OVP, OPP, OTP, SCP"
    },
    "105": {
        "Fabricante": "XPG",
        "Modelo": "Core Reactor II 850W Gold",
        "Potência": "850W",
        "Certificação": "80 Plus Gold",
        "Eficiência": "Até 91,4% (115V, 50% carga)",
        "Modularidade": "Full Modular",
        "Ventoinha": "120mm, FDB",
        "Padrão ATX": "ATX 3.0/3.1, PCIe 5.1",
        "Conector ATX": "1x 24 pinos",
        "Conector PCIe": "6x 6+2 pinos + 1x 12VHPWR (600W)",
        "Conector SATA": "8x",
        "Proteções": "OCP, OVP, OPP, OTP, UVP, SCP, NLO, SIP"
    },
    "106": {
        "Fabricante": "Cooler Master",
        "Modelo": "MWE 650 Bronze V2",
        "Potência": "650W",
        "Certificação": "80 Plus Bronze",
        "Eficiência": "85% (típica)",
        "Modularidade": "Não modular",
        "Ventoinha": "120mm, HDB",
        "Padrão ATX": "ATX 2.52",
        "Conector ATX": "1x 24 pinos",
        "Conector PCIe": "4x 6+2 pinos",
        "Conector SATA": "6x",
        "Garantia": "5 Anos"
    },
    "107": {
        "Fabricante": "Corsair",
        "Modelo": "RM850e 850W Gold",
        "Potência": "850W",
        "Certificação": "80 Plus Gold (Cybenetics Gold)",
        "Eficiência": "Até 90%",
        "Modularidade": "Full Modular (Tipo 4)",
        "Ventoinha": "120mm",
        "Padrão ATX": "ATX 3.1, PCIe 5.1",
        "Conector ATX": "1x 24 pinos",
        "Conector EPS": "2x 8 pinos",
        "Conector PCIe": "3x + 1x 12V-2x6 nativo (600W)",
        "MTBF": "100.000 horas"
    },
    "108": {
        "Fabricante": "MSI",
        "Modelo": "MAG A850GL PCIE5 850W Gold",
        "Potência": "850W",
        "Certificação": "80 Plus Gold",
        "Eficiência": "Até 90%",
        "Modularidade": "Full Modular",
        "Ventoinha": "120mm",
        "Padrão ATX": "ATX 3.0, PCIe 5.0",
        "Conector ATX": "1x 20+4 pinos",
        "Conector PCIe": "1x 16 pinos + 4x 6+2 pinos",
        "Conector SATA": "8x",
        "Proteções": "OCP, OVP, OPP, OTP, SCP, UVP"
    },
    "109": {
        "Fabricante": "DeepCool",
        "Modelo": "PX850G",
        "Potência": "850W",
        "Certificação": "80 Plus Gold (Cybenetics Gold)",
        "Eficiência": "> 90% (50% carga)",
        "Modularidade": "Full Modular",
        "Ventoinha": "135mm, FDB",
        "Padrão ATX": "ATX 3.0, PCIe 5.0",
        "Conector ATX": "1x 20+4 pinos",
        "Conector PCIe": "3x 6+2 pinos + 1x 12VHPWR (16 pinos)",
        "Conector SATA": "4x",
        "Proteções": "OPP, OVP, SCP, OTP, OCP, UVP"
    },
    "110": {
        "Fabricante": "Thermaltake",
        "Modelo": "oughpower GF A3 750W",
        "Potência": "750W",
        "Certificação": "80 Plus Gold (Cybenetics Platinum)",
        "Eficiência": "Até 90%",
        "Modularidade": "Full Modular",
        "Ventoinha": "120mm, FDB (1500 RPM máx.)",
        "Padrão ATX": "ATX 3.0, PCIe 5.0",
        "Conector ATX": "1x 24 pinos",
        "Conector PCIe": "3x + 1x 12VHPWR (300W)",
        "Conector SATA": "2x",
        "Proteções": "Proteções"
    },
    "111": {
        "Fabricante": "LG",
        "Modelo": "UltraGear 24GN60R-B",
        "Tamanho da tela": "24\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "IPS",
        "Taxa de atualização": "144Hz",
        "Tempo de resposta": "1ms (GtG)",
        "Brilho": "300 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium",
        "Conexões": "1x HDMI, 1x DisplayPort",
        "Ajustes": "Inclinação"
    },
    "112": {
        "Fabricante": "LG",
        "Modelo": "27GN750-B",
        "Tamanho da tela": "27\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "IPS",
        "Taxa de atualização": "240Hz",
        "Tempo de resposta": "1ms (GtG)",
        "Brilho": "400 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "NVIDIA G-Sync Compatible, AMD FreeSync Premium",
        "Conexões": "2x HDMI, 1x DisplayPort",
        "Ajustes": "Inclinação"
    },
    "113": {
        "Fabricante": "Samsung",
        "Modelo": "Odyssey G3",
        "Tamanho da tela": "24\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "VA",
        "Taxa de atualização": "144Hz",
        "Tempo de resposta": "1ms (MPRT)",
        "Brilho": "250 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium",
        "Conexões": "1x VGA, 1x DisplayPort 1.2, 1x HDMI 2.0",
        "Ajustes": "Altura, inclinação, rotação, pivô"
    },
    "114": {
        "Fabricante": "Samsung",
        "Modelo": "Odyssey G5 (G55C)",
        "Tamanho da tela": "27\"",
        "Resolução": "QHD (2560x1440)",
        "Tipo de painel": "VA (curvo 1000R)",
        "Taxa de atualização": "165Hz",
        "Tempo de resposta": "1ms (MPRT)",
        "Brilho": "300 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync",
        "Conexões": "1x DisplayPort 1.2, 1x HDMI 2.0",
        "Ajustes": "Inclinação"
    },
    "115": {
        "Fabricante": "Samsung",
        "Modelo": "Odyssey G4 (G40B / LS25BG402)",
        "Tamanho da tela": "25\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "IPS",
        "Taxa de atualização": "240Hz",
        "Tempo de resposta": "1ms (GtG)",
        "Brilho": "400 cd/m²",
        "Ângulo de visão": "178°",
        "Sincronização": "NVIDIA G-Sync Compatible, AMD FreeSync Premium",
        "Conexões": "1x DisplayPort 1.2, 2x HDMI 2.0",
        "Ajustes": "Giro, inclinação, altura (Ultrawide Game View 21:9)"
    },
    "116": {
        "Fabricante": "AOC",
        "Modelo": "24G2S/BK",
        "Tamanho da tela": "24\"",
        "Resolução": "Full HD (1920x1080",
        "Tipo de painel": "VA",
        "Taxa de atualização": "165Hz (DP) / 144Hz (HDMI)",
        "Tempo de resposta": "1ms (MPRT)",
        "Brilho": "350 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium",
        "Conexões": "1x VGA, 2x HDMI 1.4, 1x DisplayPort 1.2",
        "Ajustes": "Altura, giro, inclinação, pivô"
    },
    "117": {
        "Fabricante": "AOC",
        "Modelo": "27G2S/BK",
        "Tamanho da tela": "27\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "VA",
        "Taxa de atualização": "165Hz (DP) / 144Hz (HDMI)",
        "Tempo de resposta": "1ms (MPRT)",
        "Brilho": "350 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync",
        "Conexões": "1x VGA, 2x HDMI 1.4, 1x DisplayPort 1.2",
        "Ajustes": "Altura, inclinação, rotação"
    },
    "118": {
        "Fabricante": "ASUS",
        "Modelo": "TUF Gaming VG249Q1A",
        "Tamanho da tela": "24\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "IPS",
        "Taxa de atualização": "165Hz OC",
        "Tempo de resposta": "1ms (MPRT)",
        "Brilho": "250 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium, Adaptive-Sync",
        "Conexões": "1x DisplayPort 1.2, 2x HDMI 1.4",
        "Ajustes": "Inclinação"
    },
    "119": {
        "Fabricante": "ASUS",
        "Modelo": "TUF Gaming VG27AQ3A",
        "Tamanho da tela": "27\"",
        "Resolução": "QHD (2560x1440)",
        "Tipo de painel": "Fast IPS",
        "Taxa de atualização": "180Hz",
        "Tempo de resposta": "1ms (GTG)",
        "Brilho": "250 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium, NVIDIA G-Sync Compatible",
        "Conexões": "HDMI, DisplayPort",
        "Ajustes": "ELMB Sync, Variable Overdrive"
    },
    "120": {
        "Fabricante": "Gigabyte",
        "Modelo": "G24F 2",
        "Tamanho da tela": "24\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "SS IPS",
        "Taxa de atualização": "OC 180Hz",
        "Tempo de resposta": "1ms (MPRT)",
        "Brilho": "300 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium",
        "Conexões": "2x HDMI 2.0, 1x DisplayPort 1.2",
        "Ajustes": "Altura, inclinação"
    },
    "121": {
        "Fabricante": "Gigabyte",
        "Modelo": "M27Q",
        "Tamanho da tela": "27\"",
        "Resolução": "QHD (2560x1440)",
        "Tipo de painel": "SS IPS",
        "Taxa de atualização": "OC 170Hz",
        "Tempo de resposta": "0,5ms (MPRT)",
        "Brilho": "350 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium",
        "Conexões": "2x HDMI 2.0, 1x DisplayPort 1.2, USB-C",
        "Ajustes": "Altura, inclinação"
    },
    "122": {
        "Fabricante": "MSI",
        "Modelo": "G244F",
        "Tamanho da tela": "24\"",
        "Resolução": "Full HD (1920x1080)",
        "Tipo de painel": "Rapid IPS",
        "Taxa de atualização": "170Hz (DP) / 165Hz (HDMI)",
        "Tempo de resposta": "1ms (GtG)",
        "Brilho": "250 cd/m²",
        "Ângulo de visão": "178°/178°",
        "Sincronização": "AMD FreeSync Premium",
        "Conexões": "2x HDMI 2.0b, 1x DisplayPort 1.2a",
        "Ajustes": "Inclinação"
    },
    "123": {
        "Fabricante": "MSI",
        "Modelo": "MAG 274QRFW",
        "Tamanho da tela": "27\"",
        "Resolução": "WQHD (2560x1440)",
        "Tipo de painel": "Rapid IPS",
        "Taxa de atualização": "180Hz",
        "Tempo de resposta": "1ms (GtG)",
        "Contraste": "1000:1",
        "Ângulo de visão": "178°",
        "Sincronização": "Adaptive-Sync",
        "Conexões": "HDMI, DisplayPort",
        "Ajustes": "inclinação, altura, giro, pivô"
    },
    "124": {
        "Fabricante": "NVIDIA",
        "Modelo": "GTX 1060",
        "Memória": "6 GB",
        "Tipo de memória": "GDDR5",
        "Barramento de memória": "192-bit",
        "Núcleos CUDA": "1280",
        "Clock base": "1506 MHz",
        "Clock boost": "1708 MHz",
        "TDP": "120W",
        "Conector de energia": "1x 6-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "125": {
        "Fabricante": "NVIDIA",
        "Modelo": "GTX 1070",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR5",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "1920",
        "Clock base": "1506 MHz",
        "Clock boost": "1683 MHz",
        "TDP": "150W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "126": {
        "Fabricante": "NVIDIA",
        "Modelo": "RTX 2060",
        "Memória": "6 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "192-bit",
        "Núcleos CUDA": "1920",
        "Clock base": "1365 MHz",
        "Clock boost": "1680 MHz",
        "TDP": "160W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "127": {
        "Fabricante": "NVIDIA",
        "Modelo": "RTX 2070",
        "Memória": "8GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "2304",
        "Clock base": "1410 MHz",
        "Clock boost": "1620 MHz",
        "TDP": "175W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "128": {
        "Fabricante": "NVIDIA",
        "Modelo": "RTX 3070",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "5888",
        "Clock base": "1500 MHz",
        "Clock boost": "1725 MHz",
        "TDP": "220W",
        "Conector de energia": "2x 8-pin (ou 1x 12-pin)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "129": {
        "Fabricante": "NVIDIA",
        "Modelo": "RTX 3080",
        "Memória": "10 GB",
        "Tipo de memória": "GDDR6X",
        "Barramento de memória": "320-bit",
        "Núcleos CUDA": "8704",
        "Clock base": "1440 MHz",
        "Clock boost": "1710 MHz",
        "TDP": "320W",
        "Conector de energia": "2x 8-pin (ou 1x 12-pin)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "130": {
        "Fabricante": "Intel",
        "Modelo": "i7-8700K",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "3,7 GHz",
        "Clock boost": "4,7 GHz",
        "Cache L3": "12 MB",
        "TDP": "95W",
        "Socket": "LGA1151",
        "Litografia": "14nm",
        "Memória suportada": "DDR4 até 2666MHz",
        "Gráficos integrados": "Intel UHD 630"
    },
    "131": {
        "Fabricante": "Intel",
        "Modelo": "i7-10700K",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,8 GHz",
        "Clock boost": "5,1 GHz",
        "Cache L3": "16 MB",
        "TDP": "125W",
        "Socket": "LGA1200",
        "Litografia": "14nm",
        "Memória suportada": "DDR4 até 2933MHz",
        "Gráficos integrados": "Intel UHD 630"
    },
    "132": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 5 3600",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "3,6 GHz",
        "Clock boost": "4,2 GHz",
        "Cache L3": "32 MB",
        "TDP": "65W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "133": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 5800X",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,8 GHz",
        "Clock boost": "4,7 GHz",
        "Cache L3": "32 MB",
        "TDP": "105W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "134": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 580",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR5",
        "Barramento de memória": "256-bit",
        "Stream Processors": "2304",
        "Clock base": "1257 MHz",
        "Clock boost": "1340 MHz",
        "TDP": "185W",
        "Conector de energia": "1x 6-pin + 1x 8-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "135": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 6600 XT",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "128-bit",
        "Stream Processors": "2048",
        "Clock (game)": "2359 MHz",
        "Clock boost": "2589 MHz",
        "TDP": "160W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 4.0 x8",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.1"
    },
    "136": {
        "Fabricante": "NVIDIA",
        "Modelo": "GeForce RTX 4070 Ti",
        "Memória": "12 GB",
        "Tipo de memória": "GDDR6X",
        "Barramento de memória": "192-Bit",
        "Núcleos CUDA": "7680",
        "Clock base": "2310 MHz",
        "Clock boost": "2610 MHz",
        "TDP": "285W",
        "Conector de energia": "1x 16-pin (12VHPWR)",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4a, 1x HDMI 2.1"
    },
    "137": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 7900 XTX",
        "Memória": "24 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "384-bit",
        "Stream Processors": "6144",
        "Clock (game)": "2300 MHz",
        "Clock boost": "2500 MHz",
        "TDP": "355W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "2x DisplayPort 2.1, 2x HDMI 2.1"
    },
    "138": {
        "Fabricante": "NVIDIA",
        "Modelo": "GTX 1660 SUPER",
        "Memória": "6 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "192-bit",
        "Núcleos CUDA": "1408",
        "Clock base": "1530 MHz",
        "Clock boost": "1785 MHz",
        "TDP": "125W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "139": {
        "Fabricante": "NVIDIA",
        "Modelo": "RTX 2060 SUPER",
        "Memória": "8 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "256-bit",
        "Núcleos CUDA": "2176",
        "Clock base": "1470 MHz",
        "Clock boost": "1650 MHz",
        "TDP": "175W",
        "Conector de energia": "1x 8-pin",
        "Interface": "PCIe 3.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.0b"
    },
    "140": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 6700",
        "Memória": "10 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "160-bit",
        "Stream Processors": "2304",
        "Clock (game)": "2450 MHz",
        "Clock boost": "2581 MHz",
        "TDP": "175W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "3x DisplayPort 1.4, 1x HDMI 2.1"
    },
    "141": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 6800 XT",
        "Memória": "16 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "256-bit",
        "Stream Processors": "4608",
        "Clock (game)": "2015 MHz",
        "Clock boost": "2250 MHz",
        "TDP": "300W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "2x DisplayPort 1.4, 2x HDMI 2.1"
    },
    "142": {
        "Fabricante": "AMD",
        "Modelo": "Radeon RX 7900 XT",
        "Memória": "20 GB",
        "Tipo de memória": "GDDR6",
        "Barramento de memória": "320-bit",
        "Stream Processors": "5376",
        "Clock (game)": "2000 MHz",
        "Clock boost": "2400 MHz",
        "TDP": "315W",
        "Conector de energia": "2x 8-pin",
        "Interface": "PCIe 4.0 x16",
        "Saídas de vídeo": "2x DisplayPort 2.1, 2x HDMI 2.1"
    },
    "143": {
        "Fabricante": "Intel",
        "Modelo": "i5-8600K",
        "Núcleos": "6",
        "Threads": "6",
        "Clock base": "3,6 GHz",
        "Clock boost": "4,3 GHz",
        "Cache L3": "9 MB",
        "TDP": "95W",
        "Socket": "LGA1151",
        "Litografia": "14nm",
        "Memória suportada": "DDR4 até 2666MHz",
        "Gráficos integrados": "Intel UHD 630"
    },
    "144": {
        "Fabricante": "Intel",
        "Modelo": "i7-11700K",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,6 GHz",
        "Clock boost": "5,0 GHz",
        "Cache L3": "16 MB",
        "TDP": "125W (251W turbo)",
        "Socket": "LGA1200",
        "Litografia": "14nm",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Intel UHD 750"
    },
    "145": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 5 5600X",
        "Núcleos": "6",
        "Threads": "12",
        "Clock base": "3,7 GHz",
        "Clock boost": "4,6 GHz",
        "Cache L3": "32 MB",
        "TDP": "65W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "146": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 7 3700X",
        "Núcleos": "8",
        "Threads": "16",
        "Clock base": "3,6 GHz",
        "Clock boost": "4,4 GHz",
        "Cache L3": "32 MB",
        "TDP": "65 W",
        "Socket": "AM4",
        "Litografia": "7nm (TSMC)",
        "Memória suportada": "DDR4 até 3200MHz",
        "Gráficos integrados": "Não possui"
    },
    "147": {
        "Fabricante": "AMD",
        "Modelo": "Ryzen 9 7900X",
        "Núcleos": "12",
        "Threads": "24",
        "Clock base": "4,7 GHz",
        "Clock boost": "5,6 GHz",
        "Cache L3": "64 MB",
        "TDP": "170W",
        "Socket": "AM5",
        "Litografia": "5nm (TSMC)",
        "Memória suportada": "DDR5 até 5200MHz",
        "Gráficos integrados": "Radeon Graphics (RDNA2, 2 CUs)"
    },
    "148": {
        "Fabricante": "Gigabyte",
        "Modelo": "B450M DS3H V2",
        "Chipset": "AMD B450",
        "Socket": "AM4",
        "CPUs suportadas": "Ryzen 5000/3000/2000 Series",
        "Memória RAM": "4x DDR4, até 64GB",
        "Slots PCIe": "1x PCIe 3.0 x16 + 1x PCIe 2.0 x1",
        "Slots M.2": "1 (PCIe 3.0 x4)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "4 fases, entrada",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.1 Gen1"
    },
    "149": {
        "Fabricante": "ASUS",
        "Modelo": "TUF Gaming B450M-PLUS",
        "Chipset": "AMD B450",
        "Socket": "AM4",
        "CPUs suportadas": "Ryzen 5000/4000/3000/2000 Series",
        "Memória RAM": "4x DDR4, até 128GB",
        "Slots PCIe": "1x PCIe 3.0 x16 + 1x PCIe 2.0 x1",
        "Slots M.2": "1 (PCIe 3.0/SATA)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "6 fases",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.1 Gen2 Type-A"
    },
    "150": {
        "Fabricante": "MSI",
        "Modelo": "B450 Tomahawk MAX II",
        "Chipset": "AMD B450",
        "Socket": "AM4",
        "CPUs suportadas": "Ryzen 5000/4000/3000/2000 Series",
        "Memória RAM": "4x DDR4, até 128GB, OC até 4400+MHz",
        "Slots PCIe": "1x PCIe 3.0 x16 + 1x PCIe 2.0 x16 (x4) + 1x PCIe 2.0 x1",
        "Slots M.2": "2 (PCIe 3.0)",
        "Portas SATA": "6x SATA 6Gb/s",
        "VRM (fases)": "8 fases",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen2 Type-A"
    },
    "151": {
        "Fabricante": "ASUS",
        "Modelo": "Prime H610M-K D4",
        "Chipset": "Intel H610",
        "Socket": "LGA 1700",
        "CPUs suportadas": "Intel Core 12ª/13ª/14ª geração (sem overclock)",
        "Memória RAM": "2x DDR4, até 48-64GB",
        "Slots PCIe": "1x PCIe 3.0 x16 + 1x PCIe 3.0 x1",
        "Slots M.2": "1 (PCIe 3.0 x4)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "4+1 fases",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen1"
    },
    "152": {
        "Fabricante": "Gigabyte",
        "Modelo": "H610M H",
        "Chipset": "Intel H610",
        "Socket": "LGA 1700",
        "CPUs suportadas": "Intel Core 12ª/13ª/14ª geração (sem overclock)",
        "Memória RAM": "2x DDR4, até 64GB",
        "Slots PCIe": "1x PCIe 3.0 x16 + 1x PCIe 3.0 x1",
        "Slots M.2": "1 (PCIe 3.0 x4)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "4 fases, entrada",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen1"
    },
    "153": {
        "Fabricante": "MSI",
        "Modelo": "PRO B660M-A",
        "Chipset": "Intel B660",
        "Socket": "LGA 1700",
        "CPUs suportadas": "Intel Core 12ª/13ª geração",
        "Memória RAM": "4x DDR4, até 128GB",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x1",
        "Slots M.2": "2 (1x PCIe 4.0 + 1x PCIe 3.0)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "8 Fases",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen2 Type-C"
    },
    "154": {
        "Fabricante": "ASUS",
        "Modelo": "TUF Gaming B760M PLUS D4",
        "Chipset": "Intel B760",
        "Socket": "LGA 1700",
        "CPUs suportadas": "Intel Core 14ª/13ª/12ª geração",
        "Memória RAM": "4x DDR4, até 128GB",
        "Slots PCIe": "1x PCIe 4.0 x16 + 1x PCIe 3.0 x16 (x4)",
        "Slots M.2": "2 (1x PCIe 4.0 via CPU + 1x PCIe 3.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "8+1 fases DrMOS",
        "Rede": "Sem WiFi nativo, LAN 1Gb",
        "USB": "USB 3.2 Gen2 Type-C"
    },
    "155": {
        "Fabricante": "Gigabyt",
        "Modelo": "X670 AORUS ELITE AX",
        "Chipset": "AMD X670",
        "Socket": "AM5",
        "CPUs suportadas": "Ryzen 9000/8000/7000 Series",
        "Memória RAM": "4x DDR5, até 128GB, suporte EXPO",
        "Slots PCIe": "1x PCIe 4.0/5.0 x16 + 1x PCIe 3.0 x16 (x1)",
        "Slots M.2": "4 (combinação PCIe 5.0/4.0)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "16+2+2 fases, 60A",
        "Rede": "WiFi 6E + Bluetooth 5.2 + LAN 2.5Gb",
        "USB": "USB 3.2 Gen2x2 Type-C"
    },
    "156": {
        "Fabricante": "ASUS",
        "Modelo": "ROG Strix B650-A Gaming WiFi",
        "Chipset": "AMD B650",
        "Socket": "AM5",
        "CPUs suportadas": "Ryzen 9000/8000/7000 Series",
        "Memória RAM": "4x DDR5, até 128GB, AEMP/EXPO",
        "Slots PCIe": "1x PCIe 4.0 x16",
        "Slots M.2": "3 (1x PCIe 5.0 via CPU + 2x PCIe 4.0/3.0 via chipset)",
        "Portas SATA": "4x SATA 6Gb/s",
        "VRM (fases)": "14+2 fases, 80A",
        "Rede": "WiFi 6E + Bluetooth + LAN 2.5Gb",
        "USB": "USB 3.2 Gen2x2 Type-C"
    },
    "157": {
        "Fabricante": "MSI",
        "Modelo": "X670E Tomahawk WiFi",
        "Chipset": "AMD X670E",
        "Socket": "AM5",
        "CPUs suportadas": "Ryzen 9000/8000/7000 Series",
        "Memória RAM": "4x DDR5, até 128GB, suporte EXPO",
        "Slots PCIe": "1x PCIe 5.0 x16 + 1x PCIe 4.0 x4",
        "Slots M.2": "4 (combinação PCIe 5.0/4.0)",
        "Portas SATA": "4-6x SATA 6Gb/s",
        "VRM (fases)": "18+2+1 fases, 80A",
        "Rede": "WiFi 6E + Bluetooth 5.3 + LAN 2.5Gb",
        "USB": "USB4 / USB 3.2 Gen2x2 Type-C"
    },
    "158": {
        "Fabricante": "Kingston",
        "Modelo": "NV2",
        "Capacidade": "1TB",
        "Interface": "PCIe 4.0 x4 NVMe",
        "Fator de forma": "M.2 2280",
        "NAND": "(não especificado pelo fabricante)",
        "Cache": "Sem DRAM (HMB)",
        "Leitura sequencial": "Até 3.500 MB/s",
        "Escrita sequencial": "Até 2.100 MB/s",
        "Durabilidade (TBW)": "320TB",
        "Compatibilidade": "PS5, Windows",
        "Software": "Kingston SSD Manager"
    },
    "159": {
        "Fabricante": "Kingston",
        "Modelo": "A400 (SA400S37/480G)",
        "Capacidade": "480GB",
        "Interface": "SATA Rev. 3.0 (6 Gb/s)",
        "Fator de forma": "2,5\" (7mm)",
        "NAND": "TLC",
        "Controlador": "Última geração (genérico)",
        "Leitura sequencial": "Até 500 MB/s",
        "Escrita sequencial": "Até 450 MB/s",
        "Software": "Kingston SSD Manager",
        "Vida útil (MTTF)": "1 milhão de horas",
        "Garantia": "3 Anos"
    },
    "160": {
        "Fabricante": "Samsung",
        "Modelo": "NVMe M.2 Samsung 990 PRO 2TB",
        "Capacidade": "2TB",
        "Interface": "PCIe Gen 4.0 x4, NVMe 2.0",
        "Fator de forma": "M.2 2280",
        "NAND": "V-NAND TLC",
        "Cache": "DRAM DDR4 2GB",
        "Leitura sequencial": "Até 7.450 MB/s",
        "Escrita sequencial": "Até 6.900 MB/s",
        "Durabilidade (TBW)": "1.200 TB",
        "Compatibilidade": "PS5, Windows, macOS",
        "Software": "Samsung Magician"
    },
    "161": {
        "Fabricante": "Samsung",
        "Modelo": "980 PRO",
        "Capacidade": "1TB",
        "Interface": "PCIe 4.0 x4, NVMe 1.3c",
        "Fator de forma": "M.2 2280",
        "NAND": "Samsung V-NAND TLC",
        "Cache": "DRAM LPDDR4",
        "Leitura sequencial": "Até 7.000 MB/s",
        "Escrita sequencial": "Até 5.000 MB/s",
        "Durabilidade (TBW)": "600 TB",
        "Compatibilidade": "Windows, macOS",
        "Software": "Samsung Magician"
    },
    "162": {
        "Fabricante": "Western Digital (WD Blue)",
        "Modelo": "SN580",
        "Capacidade": "1TB",
        "Interface": "PCIe Gen4 x4, NVMe 1.4b",
        "Fator de forma": "M.2 2280",
        "NAND": "TLC 3D NAND (BiCS5)",
        "Cache": "HMB (sem DRAM dedicada)",
        "Leitura sequencial": "Até 4.150 MB/s",
        "Escrita sequencial": "Até 4.150 MB/s",
        "Durabilidade (TBW)": "600 TB",
        "Compatibilidade": "Windows, notebooks",
        "Software": "WD SSD Dashboard"
    },
    "163": {
        "Fabricante": "Western Digital (WD_Black)",
        "Modelo": "SN850X",
        "Capacidade": "2TB",
        "Interface": "PCIe Gen4 x4, NVMe",
        "Fator de forma": "M.2 2280",
        "NAND": "TLC 3D NAND",
        "Cache": "DRAM",
        "Leitura sequencial": "Até 7.300 MB/s",
        "Escrita sequencial": "Até 6.600 MB/s",
        "Durabilidade (TBW)": "1.200 TB",
        "CompatibilidadE": "PS5, Windows 11/10/8.1",
        "Software": "WD_Black Dashboard (Game Mode 2.0)"
    },
    "164": {
        "Fabricante": "Crucial (Micron)",
        "Modelo": "P3 Plus",
        "Capacidade": "1TB",
        "Interface": "PCIe Gen4 x4, NVMe",
        "Fator de forma": "M.2 2280",
        "NAND": "Micron 3D NAND (176 camadas, QLC)",
        "Cache": "Sem DRAM (HMB)",
        "Leitura sequencial": "Até 5.000 MB/s",
        "Escrita sequencial": "Até 3.600 MB/s",
        "Durabilidade (TBW)": "220 TB",
        "Compatibilidade": "Windows, PS5 (compatível, abaixo do recomendado)",
        "Software": "Crucial Storage Executive"
    },
    "165": {
        "Fabricante": "Crucial (Micron)",
        "Modelo": "BX500 (CT500BX500SSD1)",
        "Capacidade": "500GB",
        "Interface": "SATA III 6 Gb/s",
        "Fator de Forma": "2,5\" (7mm)",
        "NAND": "Micron 3D TLC NAND",
        "Controlador": "Silicon Motion SM2258",
        "Leitura sequencial": "Até 550 MB/s",
        "Escrita sequencial": "Até 500 MB/s",
        "Durabilidade (TBW)": "120 TB",
        "Software": "Acronis True Image (clonagem)",
        "Vida útil (MTTF)": "1,5 milhão de horas"
    },
    "166": {
        "Fabricante": "Corsair",
        "Modelo": "MP600 PRO XT",
        "Capacidade": "2TB",
        "Interface": "PCIe Gen4 x4, NVMe 1.4",
        "Fator de forma": "M.2 2280",
        "NAND": "TLC de alta densidade",
        "Cache": "DRAM",
        "Leitura sequencial": "Até 7.100 MB/s",
        "Escrita sequencial": "Até 6.800 MB/s",
        "Durabilidade (TBW)": "1.400 TB",
        "Compatibilidade": "PS5, Windows",
        "Software": "Corsair SSD Toolbox"
    },
    "167": {
        "Fabricante": "Seagate",
        "Modelo": "BarraCuda 2TB 7200RPM",
        "Capacidade": "2TB",
        "Interface": "SATA 6 Gb/s",
        "Fator de forma": "3,5\"",
        "Velocidade de rotação": "7.200 RPM",
        "Cache": "256 MB",
        "Taxa de transferência": "Até 220 MB/s",
        "Ciclos de carga/descarga": "50.000",
        "Consumo (leitura/gravação)": "5,3W",
        "Nível de ruído": "Baixo (modo silencioso padrão)",
        "Compatibilidade": "Windows, Linux, Mac"
    },
    "168": {
        "Fabricante": "Seagate",
        "Modelo": "BarraCuda ST1000DM010",
        "Capacidade": "1TB",
        "Interface": "SATA 6 Gb/s",
        "Fator de forma": "3,5\"",
        "Velocidade de rotação": "7.200 RPM",
        "Cache": "64 MB",
        "Taxa de transferência": "Até 210 MB/s",
        "Ciclos de carga/descarga": "300.000",
        "Consumo (leitura/gravação)": "5,9 W",
        "Nível de ruído": "24 dBA (ocioso)",
        "Compatibilidade": "Windows, Linux, Mac"
    },
    "169": {
        "Fabricante": "Western Digital (WD Blue)",
        "Modelo": "WD20EZBX",
        "Capacidade": "2TB",
        "Interface": "SATA 6 Gb/s",
        "Fator de forma": "3,5\"",
        "Velocidade de rotação": "7.200 RPM",
        "Cache": "256 MB",
        "Taxa de transferência": "Até 215 MB/s",
        "Ciclos de carga/descarga": "300.000",
        "Nível de ruído": "Baixo (NoTouch Ramp Load)",
        "Compatibilidade": "Desktops, all-in-one",
        "Garantia": "2 Anos"
    },
    "170": {
        "Fabricante": "Toshiba",
        "Modelo": "P300 (HDWD110UZSVA)",
        "Capacidade": "1TB",
        "Interface": "SATA 6 Gb/s",
        "Fator de forma": "3,5\"",
        "Velocidade de rotação": "7.200 RPM",
        "Cache": "64 MB",
        "Consumo (leitura/gravação)": "6,4 W",
        "Compatibilidade": "Desktops, uso doméstico/escritório",
        "Taxa de transferência": "-",
        "Nível de ruído": "-",
        "Garantia": "1 Ano"
    },
    "171": {
        "Fabricante": "XPG (ADATA)",
        "Modelo": "Gammix S70 Blade",
        "Capacidade": "1TB",
        "Interface": "PCIe Gen4 x4, NVMe 1.4",
        "Fator de forma": "M.2 2280",
        "NAND": "3D NAND",
        "Cache": "DRAM",
        "Leitura sequencial": "Até 7.400 MB/s",
        "Escrita sequencial": "Até 5.500 MB/s",
        "Durabilidade (TBW)": "740 TB",
        "Compatibilidade": "PS5, Windows",
        "Software": "XPG SSD Toolbox"
    },
    "172": {
        "Fabricante": "Kingston",
        "Modelo": "FURY Renegade (SFYRD/2000G)",
        "Capacidade": "2TB",
        "Interface": "PCIe 4.0 x4 NVMe",
        "Fator de forma": "M.2 2280",
        "Controlador": "Phison E18",
        "NAND": "3D TLC",
        "Leitura sequencial": "Até 7.300 MB/s",
        "Escrita sequencial": "Até 7.000 MB/s",
        "IOPS (aleatório 4K)": "Até 1.000.000 / 1.000.000",
        "Durabilidade (TBW)": "2.000 TB (2 PBW)",
        "MTBF": "1.800.000 horas",
        "Compatibilidade": "PS5, Windows",
        "Garantia": "5 anos"
    }
};
